### ISSUE TITLE
Tree maltimap error

### ISSUE THREAD

**Issue by DriesSmit** [RobertTLange/gymnax-blines#3]
I get the following error when trying to run an example.

> Traceback (most recent call last):
>   File "./MetaBlocks/run_ippo_cartpole.py", line 17, in <module>
>     n_obs, n_state, reward, done, _ = env.step(key_step, state, action, env_params)
>   File "/mava/lib/python3.8/site-packages/gymnax/environments/environment.py", line 43, in step
>     state = jax.tree_multimap(
> AttributeError: module 'jax' has no attribute 'tree_multimap'
> make: *** [Makefile:35: run_ippo_cartpole] Error 1

Is this because the latest version of jax does not support calling `jax.tree_multimap` call anymore?

**Comment by DriesSmit** [comment]
I see there was an [issue](https://github.com/RobertTLange/gymnax/issues/27) under the gymnax repo that got closed. I am however still getting this error when using `pip install gymnax`. Show I maybe use some other method of installing gymnax?

**Comment by DriesSmit** [comment]
I see the new version was released 3 hours ago. It is fixed now :slightly_smiling_face:
